spring:
  application:
    name: ledger
  datasource:
    url: jdbc:postgresql://localhost:63175/banking_db
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
