spring:
  application:
    name: ledger
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger_db
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  kafka:
#    bootstrap-servers:
#      - localhost:9092
server:
  port: 8081
