services:
  postgres-ledger:
    image: "postgres:18.4"
    container_name: postgres-ledger
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=ledger_db"
      - "POSTGRES_PASSWORD=secret"
    volumes:
      - "ledger_data:/var/lib/postgresql/data"

  postgres-orchestrator:
    image: "postgres:18.4"
    container_name: postgres-orchestrator
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=orchestrator_db"
      - "POSTGRES_PASSWORD=secret"
    volumes:
      - "orchestrator_data:/var/lib/postgresql/data"

  redis:
    image: "redis:8.10.0"
    container_name: redis
    ports:
      - "6379"
    volumes:
      - "redis-data:/redis-data"
    restart: unless-stopped

  zipkin:
    image: "openzipkin/zipkin:latest"
    container_name: zipkin
    ports:
      - "9411:9411"

  consul:
    image: "consul:1.15"
    container_name: consul
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
      # - "8300:8300"        # Server RPC
      # - "8301:8301"        # Serf LAN (Consul communication between nodes)
      # - "8301:8301/udp"
      # - "8302:8302" # Serf WAN (Consul communication between datacenters)
      # - "8302:8302/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data -config-dir=/consul/config"
    environment:
      - CONSUL_LOCAL_CONFIG={"acl":{"enabled":true, "default_policy":"deny", "down_policy":"extend-cache"}}
      # - CONSUL_RETRY_JOIN_ADDRESS=178.18.63.42 => another cluster node IP address (Consul2)
      - CONSUL_GOSSIP_ENCRYPTION=enable
      - CONSUL_GOSSIP_ENCRYPTION_KEY=27722f556617b1ba36d5fd8e00f2c96066857838d0d80ded9c6cd70299fa1cdc
    networks:
      - consul-network
  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

volumes:
  redis-data:
    driver: local
  consul_data:
    driver: local
  consul_config:
    driver: local
  ledger_data:
    driver: local
  orchestrator_data:
    driver: local

networks:
  consul-network:
    driver: bridge
